New-Item -ItemType Directory "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste1.txt"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste2.txt"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste3.txt"
New-Item -ItemType Directory "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste\teste1.txt"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste\teste2.txt"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste\teste3.txt"
New-Item -ItemType Directory "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste2"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste2\teste1.txt"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste2\teste2.txt"
New-Item "C:\Users\rodrigo.cordeiro\Documents\Projects\preventiveAutomation\teste\teste2\teste3.txt"
