$pasta = ".\"
New-Item -ItemType Directory "$pasta\teste\"
New-Item "$pasta\teste\teste1.txt"
New-Item "$pasta\teste\teste2.txt"
New-Item "$pasta\teste\teste3.txt"
New-Item -ItemType Directory "$pasta\teste\teste"
New-Item "$pasta\teste\teste\teste1.txt"
New-Item "$pasta\teste\teste\teste2.txt"
New-Item "$pasta\teste\teste\teste3.txt"
New-Item -ItemType Directory "$pasta\teste\teste2"
New-Item "$pasta\teste\teste2\teste1.txt"
New-Item "$pasta\teste\teste2\teste2.txt"
New-Item "$pasta\teste\teste2\teste3.txt"
